### Task 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [7]:
import numpy as np
a = np.array([i for i in range(12,24)])
b = np.linspace(12, 24, 12)
print(f'a={a}, b ={b}, Почему выводятся разные массивы?')

a=[12 13 14 15 16 17 18 19 20 21 22 23], b =[12.         13.09090909 14.18181818 15.27272727 16.36363636 17.45454545
 18.54545455 19.63636364 20.72727273 21.81818182 22.90909091 24.        ], Почему выводятся разные массивы?


### Task 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [19]:
a1 = a.reshape(3,4)
a2 = a.reshape(2,6)
a3 = a.reshape(12,1)
a4 = a.reshape(6,2)
a5 = a.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

### Task 3
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [23]:
b1 = a.reshape(3, -1)
b1 = a.reshape(4, -1)
b1 = a.reshape(6, -1)
b1 = a.reshape(-1, 3)
b1 = a.reshape(-1, 4)

### Task 4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Ответ: да

### Task 5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [36]:
n = 3
m = 4
s = np.random.normal(0, 1, n*m).reshape(n,m)
print(s)
new_s = s.reshape(n*m)
new_s

[[ 0.80946828 -1.22219535  0.41098601 -0.22125661]
 [-1.35582252  0.18460137 -1.00457247  0.19327418]
 [ 3.13865929  0.53490539 -0.29363461  1.02106031]]


array([ 0.80946828, -1.22219535,  0.41098601, -0.22125661, -1.35582252,
        0.18460137, -1.00457247,  0.19327418,  3.13865929,  0.53490539,
       -0.29363461,  1.02106031])

### Task 6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [43]:
a = np.array([i for i in range(20, 0, -2)])
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Task 7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [44]:
b = np.array([i for i in range(20, 1, -2)]).reshape(1, 10)
print('Разница в том, что массив a - одномерный, а массив b - двумерный')
b

Разница в том, что массив a - одномерный, а массив b - двумерный


array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

### Task 8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [145]:
a = np.zeros((2, 2))
b = np.ones((3,2))
v = np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### Task 9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [84]:
a = np.array([i for i in range(0, 12)])
A = a.reshape(4, -1)
At = A.T
B = np.dot(A, At)
print(f'Обратной матрицы нет, потому что определить равен {np.linalg.det(B)}')

Обратной матрицы нет, потому что определить равен 0.0


### Task 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [92]:
np.random.seed(42)
mas = np.random.random(10)
mas

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

### Task 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [123]:
c = np.random.uniform(0, 16, (16))
c

array([ 5.40184274, 15.08655526,  5.17124691,  8.30064995, 11.24830334,
        5.81807364, 15.54851332, 15.39915672,  4.02851673,  7.95597609,
        4.81405296,  4.55744791,  0.59019116,  9.75302934,  8.04286437,
        0.82366002])

### Task 12
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [127]:
C = c.reshape(int(np.sqrt(c.size)), -1)
D = np.dot(C, 10) + B
print(D)
print(np.linalg.det(D))
print(np.linalg.matrix_rank(D))
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 59.01842742 164.86555263  74.71246912 115.00649948]
 [126.48303342 108.18073638 241.48513324 275.99156719]
 [ 63.28516733 165.55976094 197.14052957 257.5744791 ]
 [ 37.90191158 219.53029344 292.42864372 310.2366002 ]]
132650706.47825904
4
[[ 0.0085715   0.01022927 -0.01050884 -0.00355265]
 [ 0.00851485 -0.00229371 -0.00534683  0.00332323]
 [ 0.0028582   0.00796916 -0.02727424  0.01449544]
 [-0.00976662 -0.00713836  0.03077607 -0.01235759]]


### Task 13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [141]:
D_inv = np.where(D_inv > 0, 1, 0)
print(D_inv)
E = np.where(D_inv == 1, B, C)
E

[[1 1 0 0]
 [1 0 0 1]
 [1 1 0 1]
 [0 0 1 0]]


array([[  5.        ,  14.        ,   5.17124691,   8.30064995],
       [ 14.        ,   5.81807364,  15.54851332, 122.        ],
       [ 23.        ,  86.        ,   4.81405296, 212.        ],
       [  0.59019116,   9.75302934, 212.        ,   0.82366002]])